# Generated by Django 6.0.4 on 2026-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset_password', 'Reset Password'), ('delete_account', 'Delete Account')], max_length=50),
        ),
    ]
