# Generated by Django 6.0.4 on 2026-04-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset_password', 'Reset Password'), ('delete_account', 'Delete Account'), ('change_password', 'Change Password')], max_length=50),
        ),
    ]
